baseURL = "http://localhost:3000/"
languageCode = "en-uk"
title = "FI - Atomistic Modelling Lab"
theme = 'terminal-tutorial'

# Enable code fences highlighting
pygmentsUseClasses = true
pygmentsCodefences = true

[Params]
  author = "Denis Kramer"

  vnc_host = "vnc.kube.kramergroup.science"
  vnc_port = 443
  vnc_path = "chem6136"
  vnc_pass = ""
