version: "3"

services:
  web:
    build: .
    command: sh -c "yarn install && NODE_ENV=development yarn start"
    container_name: node
    volumes:
      - .:/app
      - /app/node_modules
      - ./public:/app/public
    tty: true
    working_dir: /app
    ports:
      - "3000:3000"
#    environment:
#      - AUTH_REQUEST_REDIRECT_URI=http://dft-lab.kramergroup.science
#      - AUTH_REQUEST_ID=31750f49c73255d846df
#      - AUTH_REQUEST_SECRET=1f2a00c4ef7fe7e923ed60fbaa6b45ca822f20ed
  hugo:
    container_name: hugo
    image: klakegg/hugo:latest
    command: --watch
    volumes:
      - .:/src
      - ./public:/target
    ports:
      - "1313:1313"
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
volumes:
  public:

