version: "3"

services:
  web:
    build: 
      context: .
      dockerfile: assets/web/Dockerfile.dev
    command: sh -c "yarn install && NODE_ENV=development yarn concurrently npm:start:client npm:start:server npm:start:hostmgr"
    container_name: web
    volumes:
      - .:/app
      - ./site:/app/public
      - ./dist/bin:/app/bin
    tty: true
    working_dir: /app
    ports:
      - "3000:3000"
  
  backend:
    build: 
      context: .
      dockerfile: assets/backend/Dockerfile
    container_name: backend
    tty: true
    privileged: true

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  
  ldap:
    container_name: ldap
    image: osixia/openldap
    ports:
      - "389:389" 
      - "636:636"
    # environment:
    #   - LDAP_DOMAIN="test.com"
    #   - LDAP_ADMIN_PASSWORD="JonSn0w"

volumes:
  public:

