version: "3"

services:
  web:
    build: .
    command: sh -c "yarn --dev && hugo && NODE_ENV=development node bin"
    volumes:
      - .:/app
      - /app/node_modules
    tty: true
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      SSHHOST: 'localhost'
      SSHPORT: 22
