# -------------------------------------------------------------------------------------------------
FROM golang:1.10 as hostmgr-builder

RUN git clone https://github.com/kramergroup/hostmgr.git /go/src/github.com/kramergroup/hostmgr
WORKDIR /go/src/github.com/kramergroup/hostmgr
RUN CGO_ENABLED=1 go build -o hostmgr cmd/hostmgr/main.go

# -------------------------------------------------------------------------------------------------
FROM node:10.14.0-stretch
MAINTAINER d.kramer@soton.ac.uk

RUN apt-get update -y && \
    apt-get install -y python bash git nano vim && \
    rm -rf /var/lib/apt/lists/*

COPY terminal/prompt.sh /etc/profile.d/prompt.sh
COPY terminal/env.sh /etc/profile.d/env.sh
COPY terminal/motd /etc/motd
COPY terminal/bashrc /etc/skel/.bashrc

EXPOSE 3000

WORKDIR /app

# Configure ssh environment
COPY --from=hostmgr-builder /go/src/github.com/kramergroup/hostmgr/hostmgr /usr/sbin/hostmgr
COPY assets/web/ssh_config /etc/ssh/ssh_config

# Entrypoint (do not define in dev environment)