# -------------------------------------------------------------------------------------------------
FROM node:10.14.0-stretch
MAINTAINER d.kramer@soton.ac.uk

RUN apt-get update -y && \
    apt-get install -y python bash git nano vim && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 3000

WORKDIR /app

# Configure ssh environment
COPY assets/web/ssh_config /etc/ssh/ssh_config

# Entrypoint (do not define in dev environment)